module About
  exposing(appFooter, appHeader, appSearch, appForm)

import Html exposing (..)
import Html.Attributes exposing (..)

appSearch: Html msg
appSearch =
    nav [ class "panel" ]
        [ p [ class "panel-heading" ]
            [ text "repositories  " ]
        , div [ class "panel-block" ]
            [ p [ class "control has-icons-left" ]
                [ input [ class "input is-small", placeholder "search", type_ "text" ]
                    []
                , span [ class "icon is-small is-left" ]
                    [ i [ class "fas fa-search" ]
                        []
                    ]
                ]
            ]
        , p [ class "panel-tabs" ]
            [ a [ class "is-active" ]
                [ text "all" ]
            , a []
                [ text "public" ]
            , a []
                [ text "private" ]
            , a []
                [ text "sources" ]
            , a []
                [ text "forks" ]
            ]
        , a [ class "panel-block is-active" ]
            [ span [ class "panel-icon" ]
                [ i [ class "fas fa-book" ]
                    []
                ]
            , text "bulma  "
            ]
        , a [ class "panel-block" ]
            [ span [ class "panel-icon" ]
                [ i [ class "fas fa-book" ]
                    []
                ]
            , text "marksheet  "
            ]
        , a [ class "panel-block" ]
            [ span [ class "panel-icon" ]
                [ i [ class "fas fa-book" ]
                    []
                ]
            , text "minireset.css  "
            ]
        , a [ class "panel-block" ]
            [ span [ class "panel-icon" ]
                [ i [ class "fas fa-book" ]
                    []
                ]
            , text "jgthms.github.io  "
            ]
        , a [ class "panel-block" ]
            [ span [ class "panel-icon" ]
                [ i [ class "fas fa-code-branch" ]
                    []
                ]
            , text "daniellowtw/infboard  "
            ]
        , a [ class "panel-block" ]
            [ span [ class "panel-icon" ]
                [ i [ class "fas fa-code-branch" ]
                    []
                ]
            , text "mojs  "
            ]
        , label [ class "panel-block" ]
            [ input [ type_ "checkbox" ]
                []
            , text "remember me  "
            ]
        , div [ class "panel-block" ]
            [ button [ class "button is-link is-outlined is-fullwidth" ]
                [ text "reset all filters    " ]
            ]
        ]



appForm: Html msg
appForm =
    div []
        [ div [ class "field" ]
            [ label [ class "label" ]
                [ text "Name" ]
            , div [ class "control" ]
                [ input [ class "input", placeholder "Text input", type_ "text" ]
                    []
                ]
            ]
        , div [ class "field" ]
            [ label [ class "label" ]
                [ text "Username" ]
            , div [ class "control has-icons-left has-icons-right" ]
                [ input [ class "input is-success", placeholder "Text input", type_ "text", value "bulma" ]
                    []
                , span [ class "icon is-small is-left" ]
                    [ i [ class "fas fa-user" ]
                        []
                    ]
                , span [ class "icon is-small is-right" ]
                    [ i [ class "fas fa-check" ]
                        []
                    ]
                ]
            , p [ class "help is-success" ]
                [ text "This username is available" ]
            ]
        , div [ class "field" ]
            [ label [ class "label" ]
                [ text "Email" ]
            , div [ class "control has-icons-left has-icons-right" ]
                [ input [ class "input is-danger", placeholder "Email input", type_ "email", value "hello@" ]
                    []
                , span [ class "icon is-small is-left" ]
                    [ i [ class "fas fa-envelope" ]
                        []
                    ]
                , span [ class "icon is-small is-right" ]
                    [ i [ class "fas fa-exclamation-triangle" ]
                        []
                    ]
                ]
            , p [ class "help is-danger" ]
                [ text "This email is invalid" ]
            ]
        , div [ class "field" ]
            [ label [ class "label" ]
                [ text "Subject" ]
            , div [ class "control" ]
                [ div [ class "select" ]
                    [ select []
                        [ option []
                            [ text "Select dropdown" ]
                        , option []
                            [ text "With options" ]
                        ]
                    ]
                ]
            ]
        , div [ class "field" ]
            [ label [ class "label" ]
                [ text "Message" ]
            , div [ class "control" ]
                [ textarea [ class "textarea", placeholder "Textarea" ]
                    []
                ]
            ]
        , div [ class "field" ]
            [ div [ class "control" ]
                [ label [ class "checkbox" ]
                    [ input [ type_ "checkbox" ]
                        []
                    , text "I agree to the "
                    , a [ href "#" ]
                        [ text "terms and conditions" ]
                    ]
                ]
            ]
        , div [ class "field" ]
            [ div [ class "control" ]
                [ label [ class "radio" ]
                    [ input [ name "question", type_ "radio" ]
                        []
                    , text "Yes    "
                    ]
                , label [ class "radio" ]
                    [ input [ name "question", type_ "radio" ]
                        []
                    , text "No    "
                    ]
                ]
            ]
        , div [ class "field is-grouped" ]
            [ div [ class "control" ]
                [ button [ class "button is-link" ]
                    [ text "Submit" ]
                ]
            , div [ class "control" ]
                [ button [ class "button is-text" ]
                    [ text "Cancel" ]
                ]
            ]
        ]
appHeader: Html msg
appHeader = 
    div [ class "container" ]
        [ h1 [ class "title" ]
            [ text "Bublegum UI Builder" ]
        , p [ class "subtitle" ]
            [ text "Create structure documents"
            ]
        ]

appFooter : Html msg
appFooter =
    footer [ class "footer" ]
        [ div [ class "container" ]
            [ div [ class "content has-text-centered" ]
                [ p []
                    [ strong []
                        [ text "Bublegum UI Builder" ]
                    , text " by "
                    , a [ href "https://github.com/olih" ]
                        [ text "Olivier Huin" ]
                    , text ". The source code is licensed under BSD3"
                    ]
                ]
            ]
        ]